[package]
name = "rsm"
version = "0.1.0"
authors = ["Cristian Kubis <cristian.kubis@tsunix.de>"]

[dependencies]
libc = "0.2.43"
clap = "2.32.0"
failure = "0.1.2"
log = "0.4.4"
fern = "0.5.6"
sqlite = "0.23.9"
mktemp = "0.3.1"
ansi_term = "0.11.0"
